/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg360project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akis Sougias
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    void populateTable(String x) {
        try {
            ResultSet tablefill2 = Login.stmt.executeQuery(x);
            while (tableP.getRowCount() > 0) {
                ((DefaultTableModel) tableP.getModel()).removeRow(0);
            }

            int col = tablefill2.getMetaData().getColumnCount();

            while (tablefill2.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {
                    rows[i - 1] = tablefill2.getObject(i);
                }
                ((DefaultTableModel) tableP.getModel()).insertRow(tablefill2.getRow() - 1, rows);
            }
            tablefill2.close();
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // PINAKAS STHN DIAGNVSH
    void populateTable2(String x) {
        try {
            ResultSet tablefill3 = Login.stmt.executeQuery(x);
            while (tableP2.getRowCount() > 0) {
                ((DefaultTableModel) tableP2.getModel()).removeRow(0);
            }

            int col = tablefill3.getMetaData().getColumnCount();

            while (tablefill3.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {
                    rows[i - 1] = tablefill3.getObject(i);
                }
                ((DefaultTableModel) tableP2.getModel()).insertRow(tablefill3.getRow() - 1, rows);
            }
            tablefill3.close();
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // PINAKAS ASTHENWN GIA FARMAKA
    void populateTable3(String x) {
        try {
            ResultSet tablefill4 = Login.stmt.executeQuery(x);
            while (tablePa.getRowCount() > 0) {
                ((DefaultTableModel) tablePa.getModel()).removeRow(0);
            }

            int col = tablefill4.getMetaData().getColumnCount();

            while (tablefill4.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {
                    rows[i - 1] = tablefill4.getObject(i);
                }
                ((DefaultTableModel) tablePa.getModel()).insertRow(tablefill4.getRow() - 1, rows);
            }
            tablefill4.close();
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void populateTable4(String x) {
        try {
            ResultSet tablefill4 = Login.stmt.executeQuery(x);
            while (tableM.getRowCount() > 0) {
                ((DefaultTableModel) tableM.getModel()).removeRow(0);
            }

            int col = tablefill4.getMetaData().getColumnCount();

            while (tablefill4.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {
                    rows[i - 1] = tablefill4.getObject(i);
                }
                ((DefaultTableModel) tableM.getModel()).insertRow(tablefill4.getRow() - 1, rows);
            }
            tablefill4.close();
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Doctor() {

        initComponents();

        String patients = "SELECT * FROM PATIENT"
                + " WHERE patient.status = 1";
        populateTable(patients);

        String patients2 = "SELECT * FROM PATIENT"
                + " WHERE patient.status = 3";
        populateTable2(patients2);

        String patients3 = "SELECT * FROM PATIENT"
                + " WHERE patient.status = 4";
        populateTable3(patients3);

        String patients4 = "SELECT * FROM medicine";
        populateTable4(patients4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        amkaF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        urine = new javax.swing.JCheckBox();
        supersonic = new javax.swing.JCheckBox();
        heart = new javax.swing.JCheckBox();
        blood = new javax.swing.JCheckBox();
        covid = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableP = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        amkaF2 = new javax.swing.JTextField();
        f1 = new javax.swing.JCheckBox();
        f2 = new javax.swing.JCheckBox();
        f3 = new javax.swing.JCheckBox();
        f4 = new javax.swing.JCheckBox();
        f5 = new javax.swing.JCheckBox();
        send2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablePa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableM = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        amkaF1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        send1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableP2 = new javax.swing.JTable();
        covid19 = new javax.swing.JRadioButton();
        flu = new javax.swing.JRadioButton();
        otitis = new javax.swing.JRadioButton();
        egkefaliko = new javax.swing.JRadioButton();
        katagma = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        jLabel2.setText("Τμήμα Επιγόντων Περιστατικών");

        jButton1.setText("Αποσύνδεση");

        jLabel5.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        jLabel5.setText("Καλαμιτσίου");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        amkaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amkaFActionPerformed(evt);
            }
        });

        jLabel13.setText("AMKA Ασθενή");

        send.setText("Παραγγελία εξετάσεων");
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        urine.setText("Urine Test");
        urine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urineActionPerformed(evt);
            }
        });

        supersonic.setText("Supersonic");

        heart.setText("Heart Pulse Test");

        blood.setText("Blood Test");

        covid.setText("Covid-19 test");

        tableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ΑΜΚΑ", "Όνομα", "Επίθετο", "Φύλλο", "Ασφάλεια", "Τηλέφωνο", "Διεύθυνση", "Χρόνια Ν.", "Αλλεργίες", "Κατάσταση"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send)
                    .addComponent(covid)
                    .addComponent(blood)
                    .addComponent(heart)
                    .addComponent(supersonic)
                    .addComponent(urine)
                    .addComponent(amkaF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amkaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(urine)
                        .addGap(35, 35, 35)
                        .addComponent(supersonic)
                        .addGap(42, 42, 42)
                        .addComponent(heart)
                        .addGap(42, 42, 42)
                        .addComponent(blood)
                        .addGap(45, 45, 45)
                        .addComponent(covid)
                        .addGap(33, 33, 33)
                        .addComponent(send))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Παραγγελία Εξετασεων", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("      Εφημερία      ", jPanel5);

        jLabel15.setText("AMKA Ασθενή");

        amkaF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amkaF2ActionPerformed(evt);
            }
        });

        f1.setText("Advil");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        f2.setText("Acetamoniphen");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f3.setText("Amoxyl");

        f4.setText("Augmentin");

        f5.setText("Vyzantinon");

        send2.setText("Αποστολή Συνταγής");
        send2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send2MouseClicked(evt);
            }
        });
        send2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send2ActionPerformed(evt);
            }
        });

        tablePa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ΑΜΚΑ", "Όνομα", "Επίθετο", "Φύλλο", "Ασφάλεια", "Τηλέφωνο", "Διεύθυνση", "Χρόνια Ν.", "Αλλεργίες", "Νόσημα"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablePa);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Ασθενείς");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Λίστα Φαρμάκων");

        tableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MID", "Όνομα", "Τύπος", "Εφαρμογή", "Ενδείνυται για", "Περιεκτικότητα"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableM);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f3)
                    .addComponent(f2)
                    .addComponent(f1)
                    .addComponent(amkaF2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send2)
                    .addComponent(f5)
                    .addComponent(f4)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(amkaF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(f1)
                        .addGap(18, 18, 18)
                        .addComponent(f2)
                        .addGap(18, 18, 18)
                        .addComponent(f3)
                        .addGap(18, 18, 18)
                        .addComponent(f4))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f5)
                    .addComponent(jLabel3))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(send2))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Παραγγελία Φαρμάκων", jPanel9);

        amkaF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amkaF1ActionPerformed(evt);
            }
        });

        jLabel14.setText("AMKA Ασθενή");

        send1.setText("Αποστολή Διάγνωσης");
        send1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send1MouseClicked(evt);
            }
        });
        send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send1ActionPerformed(evt);
            }
        });

        tableP2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ΑΜΚΑ", "Όνομα", "Επίθετο", "Φύλλο", "Ασφάλεια", "Τηλέφωνο", "Διεύθυνση", "Χρόνια Ν.", "Αλλεργίες", "Κατάσταση"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableP2);

        buttonGroup1.add(covid19);
        covid19.setText("Covid 19");

        buttonGroup1.add(flu);
        flu.setText("Flu");

        buttonGroup1.add(otitis);
        otitis.setText("Otitis");

        buttonGroup1.add(egkefaliko);
        egkefaliko.setText("Egkefaliko");

        buttonGroup1.add(katagma);
        katagma.setText("Katagma");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amkaF1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(send1)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flu)
                            .addComponent(covid19)
                            .addComponent(otitis)
                            .addComponent(egkefaliko)
                            .addComponent(katagma))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(amkaF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(covid19)
                        .addGap(18, 18, 18)
                        .addComponent(flu)
                        .addGap(18, 18, 18)
                        .addComponent(otitis)
                        .addGap(18, 18, 18)
                        .addComponent(egkefaliko)
                        .addGap(18, 18, 18)
                        .addComponent(katagma)
                        .addGap(31, 31, 31)
                        .addComponent(send1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Διάγνωση", jPanel10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amkaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amkaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amkaFActionPerformed

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        String amka = amkaF.getText();
        String sql;
        String exams = "";
        if (urine.isSelected()) {
            exams = exams + "UrineTest ";
        }
        if (supersonic.isSelected()) {
            exams = exams + "Supersonic ";
        }
        if (heart.isSelected()) {
            exams = exams + "HeartPulseTest ";
        }
        if (blood.isSelected()) {
            exams = exams + "BloodTest ";
        }
        if (covid.isSelected()) {
            exams = exams + "Covid19Test ";
        }

        sql = "UPDATE\n" +
"    patient\n" +
"SET\n" +
 "    patient.eksetaseis = '" + exams + "'\n"
                + "WHERE\n" +
 "    patient.amka =" + amka;
        try {
            Login.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Examinations Sent Succesfully!");
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }


        sql = "UPDATE\n" +
"    patient\n" +
"SET\n" +
 "    patient.status = 2\n"
                + "WHERE\n" +
 "    patient.amka =" + amka;
        try {
            Login.stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_sendMouseClicked

    private void urineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urineActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendActionPerformed

    private void amkaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amkaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amkaF1ActionPerformed

    private void send1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send1MouseClicked
        String amka = amkaF1.getText();
        String sql;
        String diagnose = "";
        if (covid19.isSelected()) {
            diagnose = "covid19";
        }else if(flu.isSelected()){
            diagnose = "flu";

        } else if (otitis.isSelected()) {
            diagnose = "otitis";

        } else if (egkefaliko.isSelected()) {
            diagnose = "egkefaliko";

        } else if (egkefaliko.isSelected()) {
            diagnose = "katagma";
        }
        sql = "UPDATE\n"
                + "    patient\n"
                + "SET\n"
                + "    patient.diagnose = '" + diagnose + "'\n"
                + "WHERE\n"
                + "    patient.amka =" + amka;
        try {
            Login.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Diagnose Sent Succesfully!");
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }

        sql = "UPDATE\n"
                + "    patient\n"
                + "SET\n"
                + "    patient.status = 4\n"
                + "WHERE\n"
                + "    patient.amka =" + amka;
        try {
            Login.stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_send1MouseClicked

    private void send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send1ActionPerformed

    private void amkaF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amkaF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amkaF2ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f1ActionPerformed

    private void send2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send2MouseClicked
        String amka = amkaF2.getText();
        String sql;
        String drugs = "";
        if (f1.isSelected()) {
            drugs = drugs + "Advil ";
        }
        if (f2.isSelected()) {
            drugs = drugs + "Acematoniphen ";
        }
        if (f3.isSelected()) {
            drugs = drugs + "Amoxyl ";
        }
        if (f4.isSelected()) {
            drugs = drugs + "Augmentin ";
        }
        if (f5.isSelected()) {
            drugs = drugs + "Vyzantinon ";
        }
        sql = "INSERT INTO RECORD (amka,date,treatment)"+
 " VALUES(" + amka + ",CURDATE(),'" + drugs + "')";

        try {
            Login.stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }

        sql = "UPDATE\n" +
"    record\n" +
"SET\n" +
"    diagnose =(\n" +
"    SELECT\n" +
"        diagnose\n" +
"    FROM\n" +
"        patient\n" +
"    WHERE\n" +
"        patient.amka = record.amka\n" +
")";
        try {
            Login.stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "STO KALO!");
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }

        sql = "UPDATE\n"
                + "    patient\n"
                + "SET\n"
                + "    patient.status = 5\n"
                + "WHERE\n"
                + "    patient.amka =" + amka;
        try {
            Login.stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_send2MouseClicked

    private void send2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send2ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amkaF;
    private javax.swing.JTextField amkaF1;
    private javax.swing.JTextField amkaF2;
    private javax.swing.JCheckBox blood;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox covid;
    private javax.swing.JRadioButton covid19;
    private javax.swing.JRadioButton egkefaliko;
    private javax.swing.JCheckBox f1;
    private javax.swing.JCheckBox f2;
    private javax.swing.JCheckBox f3;
    private javax.swing.JCheckBox f4;
    private javax.swing.JCheckBox f5;
    private javax.swing.JRadioButton flu;
    private javax.swing.JCheckBox heart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton katagma;
    private javax.swing.JRadioButton otitis;
    private javax.swing.JButton send;
    private javax.swing.JButton send1;
    private javax.swing.JButton send2;
    private javax.swing.JCheckBox supersonic;
    private javax.swing.JTable tableM;
    private javax.swing.JTable tableP;
    private javax.swing.JTable tableP2;
    private javax.swing.JTable tablePa;
    private javax.swing.JCheckBox urine;
    // End of variables declaration//GEN-END:variables
}
